### ISSUE TITLE
Persons Page

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#41]
Path: "/present/person?person_id"
Show data _relevant_ to users.

- [x] Have entries to page for each movie they were cast and/or crew for
- [x] Site Navigation
- [x] Link to IMDB page (optional)
- [ ] Link to Wiki page (optional)
- [ ] Include bio info (optional)

**Comment by BenWong1097** [comment]
Todo: Fix issue where multiple roles show as multiple elements. Just shove them in one single one.

**Comment by SaltyQuetzals** [comment]
Closed by #46
